server:
  port: 9100

spring:
  application:
    name: goods
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:todolist
    driver-class-name: org.h2.Driver
    username: sa
    password: eren_demo

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# Data source
demo:
  datasource:
    pool-name: demo
    jdbcUrl: jdbc:mysql://192.168.50.132:3306/demo_goods?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 5
    minimum-idle: 1
    idle-timeout: 20000
    username: root
    password: EREN0330DEV
