server:
  port: 9100

# Data source
demo-datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:3306/demo_goods?serverTimezone=UTC&useSSL=false
  maximum-pool-size: 5
  minimum-idle: 1
  idle-timeout: 20000
  username: root
  password: root123456
