server:
  port: 9100

spring:
  application:
    name: goods
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:todolist
    driver-class-name: org.h2.Driver
    username: sa
    password: eren_demo

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate


# Data source
demo-datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:3306/demo_goods?serverTimezone=UTC&useSSL=false
  maximum-pool-size: 5
  minimum-idle: 1
  idle-timeout: 20000
  username: root
  password: root123456
