CREATE DATABASE demo_admin;

CREATE TABLE auth_base_user (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '流水號' PRIMARY KEY,
username VARCHAR(20) NOT NULL COMMENT '使用者帳號',
password VARCHAR(120) NOT NULL COMMENT '使用者密碼',
email VARCHAR(50) NOT NULL COMMENT '電子郵件',
locked TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否鎖住',
enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否啟用',
account_expired_date DATETIME NULL COMMENT '帳號過期日',
credentials_expired_date DATETIME NULL COMMENT '密碼過期日',
create_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '創建時間',
create_by VARCHAR(20) NOT NULL COMMENT '創建者',
update_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
update_by VARCHAR(20) NOT NULL COMMENT '更新者'
)COMMENT '使用者';