CREATE DATABASE demo_auth;

CREATE TABLE auth_user (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '流水號' PRIMARY KEY,
username VARCHAR(32) NOT NULL COMMENT '用戶帳號',
password VARCHAR(120) NOT NULL COMMENT '用戶密碼',
email VARCHAR(50) NULL COMMENT '電子郵件',
description VARCHAR(100) NULL COMMENT '描述',
locked TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否鎖住',
enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否啟用',
expired_date DATETIME NULL COMMENT '過期日',
last_pwd_change_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '最後一次密碼更新日',
create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
create_by VARCHAR(32) NOT NULL COMMENT '創建者',
update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
update_by VARCHAR(32) NOT NULL COMMENT '更新者'
)COMMENT '用戶列表';

CREATE TABLE user_role(
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '流水號' PRIMARY KEY,
username VARCHAR(32) NOT NULL COMMENT '用戶帳號',
auth_role VARCHAR(32) NOT NULL COMMENT '角色代號',
enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否啟用',
create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '創建時間',
create_by VARCHAR(32) NOT NULL COMMENT '創建者',
update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
update_by VARCHAR(32) NOT NULL COMMENT '更新者'
)COMMENT '用戶角色表';