CREATE DATABASE demo_admin;

CREATE TABLE auth_user (
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用戶ID' PRIMARY KEY,
username VARCHAR(32) NOT NULL COMMENT '用戶帳號',
password VARCHAR(120) NOT NULL COMMENT '用戶密碼',
email VARCHAR(50) NULL COMMENT '電子郵件',
description VARCHAR(100) NULL COMMENT '描述',
locked TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否鎖住',
enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否啟用',
expired_date DATETIME NULL COMMENT '過期日',
last_pwd_change_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '最後一次密碼更新日',
create_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '創建時間',
create_by VARCHAR(32) NOT NULL COMMENT '創建者',
update_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
update_by VARCHAR(32) NOT NULL COMMENT '更新者'
)COMMENT '用戶列表';

CREATE TABLE auth_role(
id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色ID' PRIMARY KEY,
role_code VARCHAR(32) NOT NULL COMMENT '角色代號',
role_name VARCHAR(64) NOT NULL COMMENT '角色名稱',
parent_id BIGINT UNSIGNED NOT NULL COMMENT '上級角色ID',
create_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '創建時間',
create_by VARCHAR(32) NOT NULL COMMENT '創建者',
update_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
update_by VARCHAR(32) NOT NULL COMMENT '更新者'
)